[Interface]
Address = 10.8.0.2/24
DNS = 1.1.1.1
PrivateKey = [ВСТАВИТЬ_СЮДА_client1_private.key]

[Peer]
PublicKey = [ВСТАВИТЬ_СЮДА_server_public.key]
Endpoint = [ВНЕШНИЙ_IP_ВАШЕГО_СЕРВЕРА_ORACLE]:51820
AllowedIPs = 0.0.0.0/0









